### ISSUE TITLE
Rookie setup

### ISSUE THREAD

**Issue by iHaagcom** [JingYiJun/MOSS_backend#24]
Is it possible to host this on my own machine?
What is this?
panic: env:
required environment variable
"D_URL" is not set; required environment variable "KONG_URL"

**Comment by JingYiJun** [comment]
You'd better not self-host this. Deployment requires a lot environments like database, kong gateway and many others, and i am not intended to write some deployment wiki or one-butten docker-compose for this repository.
A another reason is even if you successfully self-host this, you won't get inference from moss since this is only a backend for wrapping api and storage, but infer server is deployed another place.
